dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  audioplayers: ^5.2.0
  google_fonts: ^6.1.0
  vcard_vcf: ^0.1.5

assets:
  - assets/fonts/
  - assets/sounds/
